server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.25.129
      database: spitdb
  redis:
    host: 192.168.25.129
  rabbitmq:
    host: 192.168.25.129
eureka:
  client:
    service-url:
      defaultZone: http://192.168.25.129:6868/eureka/
  instance:
    prefer-ip-address: true #以后布到线上后模块之间可以跨域访问
