server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.25.129:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.25.129
  rabbitmq:
    host: 192.168.25.129
jwt:
  config:
    key: tensquare
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://192.168.25.129:6868/eureka/
  instance:
    prefer-ip-address: true #以后布到线上后模块之间可以跨域访问
